### ISSUE TITLE
Ram Detection Issue

### ISSUE THREAD

**Issue by Insert5StarName** [gnmyt/MCDash#11]
Hey there seems to be an issue with Ram Detection my server running with 24GB ram is showing up as 5GB
![image](https://github.com/gnmyt/MCDash/assets/123300075/e6132b0c-7feb-4f41-be42-0fe96d6bae0f)
it correctly shows up in other plugins 
![image](https://github.com/gnmyt/MCDash/assets/123300075/45747457-b758-4eb4-9105-0cc0bd3d0f6b)

**Comment by gnmyt** [comment]
Hey! Thanks for reporting that, I'll take a look as to why this is happening :)

**Comment by gnmyt** [comment]
Thanks again for reporting. I created a PR (#12) that fixes this bug. It should work fine in the next version
