### ISSUE TITLE
Use outside of network?

### ISSUE THREAD

**Issue by electricsteve** [gnmyt/MCDash#21]
Hello, I have a quick question about your MCDash Plugin, can it be used outside of the network? I would like to use it on my server that I host on an Oracle cloud VM so me and my friend can access it on our phones and in other places, so is that possible? BTW, The project is already really good, HOW IN 2 WEEKS A REALLY GOOD MINECRAFT PLUGIN?

**Comment by electricsteve** [comment]
How do i add a label?

**Comment by gnmyt** [comment]
Hello. Yes, that is possible. MCDash automatically uses the IP 0.0.0.0, so it is reachable both locally and from the public IPv4. I have never worked with Oracle Cloud VM, but I suspect that it is enough to share the respective port (7867 by default) there and connect to it with the public IP. If this is not possible you can also use a service like [ngrok](https://ngrok.com/) or [Cloudflare Tunnels](https://www.cloudflare.com/de-de/products/tunnel/), they pass the service even without port sharing.

**Comment by gnmyt** [comment]
Hi! I am closing this issue for now. If you still need help, feel free to reopen this issue or open a new one if you have another question
