### ISSUE TITLE
Idea: Velocity/Bungeecord support

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#42]
It would be nice if you could install the plugin on a Velocity or Bungeecord proxy to manage the servers from the panel.

This is the best plugin I have ever seen!

**Comment by gnmyt** [comment]
Thank you for the feedback. Unfortunately, with the current codebase it is not possible to include MCDash directly in Bungeecord or Velocity because it was perfectly tailored to the Spigot interface. However, an extra plugin for proxies will follow as soon as I find the time. :)
