### ISSUE TITLE
Incorrect message when changing world weather

### ISSUE THREAD

**Issue by I2000C** [gnmyt/MCDash#43]
Hi, the message that is shown when you change the weather of a world is invalid:
![image](https://github.com/gnmyt/MCDash/assets/29607352/fc89f6ff-ea5b-4da1-ac7f-0e2bf0f165dc)

I think it should be more like:
![image](https://github.com/gnmyt/MCDash/assets/29607352/34613548-6355-41d5-848f-20ad732c4b5e)
but with "Weather" instead of "Time"

**Comment by gnmyt** [comment]
Oh, thanks for reporting that. I guess the wrong translation string got into the code. I'm gonna fix that now

**Comment by I2000C** [comment]
Besides, would it be possible to add a Spanish translation?
I can translate the messages

**Comment by gnmyt** [comment]
Oh wow, I would really appreciate that. I use Crowdin for translations, so you can use [that link](https://crowdin.com/project/mcdash) to get started. I just added Spanish, so it should show right up.

Thanks!
