### ISSUE TITLE
Idea: Guest Overview

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#47]
A guest login to see the stats of the server but not manage anything.

**Comment by gnmyt** [comment]
That's a good idea. But I need to make that an option and not the default behavior, as there might be some people who don't want that for privacy reasons

**Comment by marcjoancr** [comment]
Maybe could be great to have a role and user administration in order to give or remove permissions.

**Comment by VoidableMoon884** [comment]
In progress in #69
