### ISSUE TITLE
Idea: Playerlist as API

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#48]
An API to embed the player list and other statistics on another website.

**Comment by VoidableMoon884** [comment]
Yes, exactly!
Thanks!

**Comment by VoidableMoon884** [comment]
How I can login into the api?

**Comment by gnmyt** [comment]
MCDash uses Basic Auth for authentication with the API. This means that you provide an Authorization header containing the username and password, encoded as a bas64 string.

Example (Username: Test, Password: 1234):
`Test:1234` -> `VGVzdDoxMjM0` (base64 encoded) -> `Authorization: Basic VGVzdDoxMjM0` (header)

You can also use [this generator](https://www.debugbear.com/basic-auth-header-generator) to generate the header for you.
