### ISSUE TITLE
Velocity Compat?

### ISSUE THREAD

**Issue by TecEash1** [gnmyt/MCDash#50]
Hi, your plugin looks amazing. Would it work on Velocity powered servers by any chance?

**Comment by gnmyt** [comment]
Thanks! Unfortunately, as mentioned in [this issue](https://github.com/gnmyt/MCDash/issues/42#issuecomment-1685210917), the whole codebase is made for Spigot and its forks, so currently proxies won't work. However, a plugin for proxies is definitely coming.

**Comment by TecEash1** [comment]
👍 o ok, thank you! Hope you have a nice day!
