### ISSUE TITLE
Idee: Discord Integration

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#66]
Es wäre schön, wenn man einen Discord Channel eingeben kann, in dem dann angezeigt wird, wenn z.B. ein Spieler den Server betritt/verlässt, ein Spieler eine Nachricht sendet oder der Server neu startet.

Würde es auch gehen, wenn Nachrichten die in Discord geschrieben werden, auf dem Server gesendet werden?

**Comment by gnmyt** [comment]
Die Idee, das Plugin mit Discord zu verbinden find ich prinzipiell gut. Da müsste man dann aber auch eine Integration machen, die das Server-Management einfacher macht bzw. in Discord einbaut. Für die Übertragung von Chatnachrichten innerhalb von Discord und Minecraft kann ich dir [DiscordSRV](https://www.spigotmc.org/resources/discordsrv.18494/)  empfehlen. Das deckt das ganze ab

**Comment by VoidableMoon884** [comment]
DiscordSRV benutze ich schon... Aber danke!
