### ISSUE TITLE
Idee: Benutzerkonten Verwalten

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#69]
Es wäre schön, wenn der Server Operator mit einem Befehl Benutzer von dem Panel löschen kann.

**Comment by gnmyt** [comment]
Jo das machen wir. Das würde ich dann aber erweitern und die Nutzer direkt vom Panel aus verwaltbar machen und dort ein System für Berechtigungen einbauen wo man sagt Nutzer A ist Admin, Nutzer B darf Konsole und Backup und Nutzer C darf Dateien verwalten. Das wurde auch mal vorgeschlagen, jetzt würde beides aber zusammen passen

**Comment by VoidableMoon884** [comment]
Das wäre sehr gut!
