### ISSUE TITLE
Bemerkung: RAM wird nicht vollständig genutzt, evtl. zus. Feature?

### ISSUE THREAD

**Issue by pavl21** [gnmyt/MCDash#71]
Ich habe mir testweise es auf einem Server installiert, da ist mir aufgefallen das laut Oberfläche nur insgesamt 1.94GB RAM zur Verfügung stehen. Mein Problem ist, das es auf einem Server läuft der 8GB RAM hat. 
Da käme mir die Idee auf, das man im Creator zumindest angeben kann, wieviel RAM (oder auch Speicher) man verfügbar hat. Bei eventueller knapper Ressource wäre es gut, informiert zu werden (zum. bei Speicherplatz).

**Comment by gnmyt** [comment]
Nur damit ich sicherstellen kann, dass das kein Bug ist: Wenn du die Server-Jar mit einem RAM-Limiter wie `-Xmx` startest, funktioniert es dann?

Die Möglichkeit, den RAM direkt im Creator anzugeben gefällt mir aber, da lässt sich was machen.

**Comment by gnmyt** [comment]
Habe jetzt mal [im Creator](https://create.mcdash.gnmyt.dev/) eine Option hinzugefügt, den RAM einzustellen. 

![Screenshot_20231028_115934](https://github.com/gnmyt/MCDash/assets/35641351/6242ae0b-8b9e-4080-80fe-d76f7bda3bc4)
