### ISSUE TITLE
Idee: Forge/Fabric support 

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#73]
Es wäre schön, wenn es das Plugin auch als Mod gäbe!

**Comment by gnmyt** [comment]
Moin. Ich finde die Idee selbst gut. Problem ist hierbei nur, wie auch in #50 und #42 erwähnt, dass das Plugin rein von der Codebasis nur für Spigot ausgelegt ist.

Ich werde Plugins für Software wie Forge/Fabric/Velocity/Bungeecord erstellen, das wird allerdings noch dauern da ich selbst aktuell nicht allzu viel Zeit finde.
