### ISSUE TITLE
Fehler: Whitelist "zuletzt gesehen"

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#74]
![grafik](https://github.com/gnmyt/MCDash/assets/87603556/c30e4b17-0a33-4769-9fa9-be27b19d2cf6)

Bei Spielern die noch nie auf dem Sevrer waren wird bei "zuletzt gesehen" 1.1.1970 angezeigt!

**Comment by gnmyt** [comment]
Danke fürs melden! Der Bug wird in #76 gefixt und ist in der nächsten Version weg :)
