### ISSUE TITLE
Fehler: Tabellen Sprache nicht geändert

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#78]
Wenn das Dashboard auf Deutsch gestellt ist, ist die Sprache in den Tabellen immernoch Englisch!

![grafik](https://github.com/gnmyt/MCDash/assets/87603556/c0ed163c-d1d9-4641-8630-c8a0181ded43)

**Comment by gnmyt** [comment]
Vielen Dank fürs melden. Der Bug wird in #89 behoben und sobald alle Übersetzungen eingegangen sind in der neuen Version nicht mehr auftreten. :)
