### ISSUE TITLE
Unbekannter Fehler

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#79]
Hier ist der Fehler:
In dem Logfile steht auch nicht mehr drin!
![grafik](https://github.com/gnmyt/MCDash/assets/87603556/cd32a315-8226-4a28-9bfc-0f30423f6179)

**Comment by VoidableMoon884** [comment]
Inzwischen zum zweite Mal passiert!

**Comment by gnmyt** [comment]
Danke für die Einsendung. Ich erstelle gleich eine PR die den Bug beheben sollte
