### ISSUE TITLE
IDEE: Scoreboard Übersicht

### ISSUE THREAD

**Issue by VoidableMoon884** [gnmyt/MCDash#80]
Es wäre cool, wenn es einen Reiter "Scoreboard" geben würde, wo man scoreboards erstellen und verwalten könnte.

**Comment by gnmyt** [comment]
Die Idee ist prinzipiell gut. Ich denke persönlich aber, dass das ein zu spezielles Feature wäre um dafür einen eigenen Reiter zu erstellen. Die Reiter links sollten in erster Linie nur dafür da sein, um grundlegend den Server zu verwalten. Auch könnte das mit anderen Plugins in Konflikt kommen, die bereits die Scoreboard Schnittstelle verwenden. MCDash bietet bereits einen Plugin Store und es gibt auch schon einen großen Markt an Plugins, welche diese Aufgabe bereits sehr gut erledigen können. Trotzdem vielen Dank für die Einsendung! :)
