### ISSUE TITLE
[BUG] Not Loading

### ISSUE THREAD

**Issue by TecEash1** [gnmyt/MCDash#95]
When creating a password for the dashboard via the console the dashboard does not load.

**Comment by gnmyt** [comment]
Hm, it works fine for me. When you create the account via the console, do you also log in as user `CONSOLE`? Also, do errors occur in the console when you set the password or start the plugin?

**Comment by TecEash1** [comment]
No errors occur when I started the plugin. However the login screen did not load at all for some reason.

**Comment by TecEash1** [comment]
Switched to a different panel
